"""empty message

Revision ID: 13a6901fe903
Revises: None
Create Date: 2014-10-04 13:00:33.496901

"""

# revision identifiers, used by Alembic.
revision = '13a6901fe903'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_model')
    ### end Alembic commands ###
